name: CI PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Configura ambiente PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Modifica la versione PHP se necessario
          extensions: mbstring, xml, mysql, intl  # Aggiungi estensioni necessarie
          tools: composer:v2  # Specifica la versione di Composer

      - name: Cache dipendenze Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Installa dipendenze
        run: composer install --prefer-dist --no-progress

      - name: Esegui test PHPUnit
        run: ./vendor/bin/phpunit  # Modifica il percorso se necessario

      # Opzionale: Aggiungi controllo dello stile del codice
      # - name: Esegui PHP Code Sniffer
      #   run: |
      #     composer run lint
      #     composer run cs-check
